#!/bin/bash

#MAIN FUNCTION
function changeGovernor() {
    #SETTING CPU GOVERNOR
    if [ $GOVERNOR == 0 ] 
        then
            echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    fi
    if [ $GOVERNOR == 1 ]
        then
            echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    fi

    #PRINTING CURRENT CPU GOVERNOR
    CURRENT=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
    echo "INFO: Your CPU governor is set to $CURRENT"
}

#CONDITIONAL CHECKING
if [ $# -eq 0 ]
    then
        #RUNNING WITHOUT ARGUMENT
        echo "Select CPU governor mode:"
        echo "0 - Performance"
        echo "1 - Poversave"
        read GOVERNOR

        changeGovernor $GOVERNOR
    else
        #RUNNING WITH ARGUMENT TO SAVE TIME
        GOVERNOR=$1
        changeGovernor $GOVERNOR
fi